name: Build-Ci

on:
  push:
    branches:
    - petals

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build MDr-Petals
      run: |
        php .build.php
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: sci-hub-p2p-frontend-${{ matrix.node-version }}
          path: ./